# Generated by Django 4.1.3 on 2022-11-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackusername', models.CharField(max_length=30, null=True)),
                ('operation_type', models.CharField(max_length=100, null=True)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
            ],
        ),
    ]
